// Sample data for seeding Sanity CMS
// 6 artists + 12 artworks (2 per artist)

export const sampleArtists = [
  {
    _type: 'artist',
    name: { zh: '林风眠', en: 'Lin Fengmian' },
    slug: { current: 'lin-fengmian' },
    location: '北京',
    bio: {
      zh: '林风眠（1900-1991），中国现代画家、艺术教育家，被誉为"中国现代绘画之父"。他的作品融合中西，独创"林风眠格体"。',
      en: 'Lin Fengmian (1900-1991) was a pioneering Chinese modern painter and art educator, known as the "Father of Modern Chinese Painting". His work uniquely blends Chinese and Western styles.',
    },
    style: ['Abstract', 'Landscape'],
    image: null,
  },
  {
    _type: 'artist',
    name: { zh: '赵无极', en: 'Zhao Wuji' },
    slug: { current: 'zhao-wuji' },
    location: '巴黎',
    bio: {
      zh: '赵无极（1920-2013），华裔法国画家，被认为是当代最重要 的抽象画家之一。其作品将中国水墨的意境与西方抽象艺术完美融合。',
      en: 'Zhao Wuji (1920-2013) was a Chinese-born French painter considered one of the most important abstract painters of our time. His work masterfully blends Chinese ink painting sensibilities with Western abstraction.',
    },
    style: ['Abstract', 'Minimalist'],
    image: null,
  },
  {
    _type: 'artist',
    name: { zh: '潘玉良', en: 'Pan Yuliang' },
    slug: { current: 'pan-yuliang' },
    location: '上海',
    bio: {
      zh: '潘玉良（1895-1977），中国著名女画家，以其独特的裸女画和东方风格肖像闻名于世。',
      en: 'Pan Yuliang (1895-1977) was a renowned Chinese female painter, famous for her unique nudes and Eastern-style portraits.',
    },
    style: ['Portrait'],
    image: null,
  },
  {
    _type: 'artist',
    name: { zh: '吴冠中', en: 'Wu Guanzhong' },
    slug: { current: 'wu-guanzhong' },
    location: '北京',
    bio: {
      zh: '吴冠中（1919-2010），中国现代著名画家，作品融合传统水墨与西方现代艺术的影响，开创了"水墨现代化"的新局面。',
      en: 'Wu Guanzhong (1919-2010) was a leading Chinese modern painter who pioneered the modernization of Chinese ink painting, blending traditional techniques with Western modernism.',
    },
    style: ['Landscape', 'Abstract'],
    image: null,
  },
  {
    _type: 'artist',
    name: { zh: '常玉', en: 'Chang Yu' },
    slug: { current: 'chang-yu' },
    location: '巴黎',
    bio: {
      zh: '常玉（1900-1966），华裔法国画家，其作品以简约的线条和裸女题材著称，被誉为"东方马蒂斯"。',
      en: 'Chang Yu (1900-1966) was a Chinese-French painter known for his minimalist lines and nude subjects, earning him the nickname "Oriental Matisse".',
    },
    style: ['Portrait', 'Texture'],
    image: null,
  },
  {
    _type: 'artist',
    name: { zh: '刘海粟', en: 'Liu Haosu' },
    slug: { current: 'liu-haosu' },
    location: '南京',
    bio: {
      zh: '刘海粟（1896-1994），中国现代艺术教育的奠基人之一，将西方油画技法引入中国的先驱。',
      en: 'Liu Haosu (1896-1994) was a founding figure of modern Chinese art education and a pioneer in introducing Western oil painting techniques to China.',
    },
    style: ['Landscape', 'Portrait'],
    image: null,
  },
];

export const sampleArtworks = [
  // Lin Fengmian
  {
    _type: 'artwork',
    title: { zh: '渔舟唱晚', en: 'Fishing Boat at Sunset' },
    slug: { current: 'lin-fishing-boat-sunset' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_1' },
    price: 88000,
    dimensions: '68×68cm',
    medium: 'Oil on Canvas',
    category: 'Landscape',
    featured: true,
    description: {
      zh: '这幅作品以简练的笔触描绘了夕阳下渔舟归航的宁静景象，色彩温暖而富有诗意。',
      en: 'This piece depicts the serene scene of fishing boats returning at sunset with concise brushstrokes, warm colors and poetic feeling.',
    },
    images: [],
  },
  {
    _type: 'artwork',
    title: { zh: '春江水暖', en: 'Spring River Warming' },
    slug: { current: 'lin-spring-river' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_1' },
    price: 128000,
    dimensions: '80×100cm',
    medium: 'Oil on Canvas',
    category: 'Landscape',
    featured: false,
    description: {
      zh: '画面以蓝绿色调为主，表现春天江水渐暖的柔和氛围。',
      en: 'Dominated by blue-green tones, this painting captures the gentle atmosphere of spring river waters warming.',
    },
    images: [],
  },
  // Zhao Wuji
  {
    _type: 'artwork',
    title: { zh: '无题 1985', en: 'Untitled 1985' },
    slug: { current: 'zhao-untitled-1985' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_2' },
    price: 280000,
    dimensions: '195×130cm',
    medium: 'Oil on Canvas',
    category: 'Abstract',
    featured: true,
    description: {
      zh: '赵无极的典型抽象风格，蓝灰色块在画布上流动、碰撞，呈现出深邃的宇宙感。',
      en: 'A quintessential Zhao Wuji abstract piece with blue and gray masses flowing and colliding across the canvas, presenting a profound sense of the cosmos.',
    },
    images: [],
  },
  {
    _type: 'artwork',
    title: { zh: '大地之歌', en: 'Song of the Earth' },
    slug: { current: 'zhao-song-earth' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_2' },
    price: 320000,
    dimensions: '200×150cm',
    medium: 'Oil on Canvas',
    category: 'Abstract',
    featured: false,
    description: {
      zh: '大地色调与抽象形状交织，表达对自然和生命的敬畏。',
      en: 'Earth tones intertwine with abstract forms expressing reverence for nature and life.',
    },
    images: [],
  },
  // Pan Yuliang
  {
    _type: 'artwork',
    title: { zh: '裸女与镜子', en: 'Nude with Mirror' },
    slug: { current: 'pan-nude-mirror' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_3' },
    price: 158000,
    dimensions: '73×92cm',
    medium: 'Oil on Canvas',
    category: 'Portrait',
    featured: true,
    description: {
      zh: '潘玉良标志性的裸女题材，柔和的色调与优雅的线条展现了独特的东方美。',
      en: 'A signature Pan Yuliang nude piece with soft tones and elegant lines showcasing unique Eastern beauty.',
    },
    images: [],
  },
  {
    _type: 'artwork',
    title: { zh: '持扇女子', en: 'Woman Holding a Fan' },
    slug: { current: 'pan-woman-fan' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_3' },
    price: 98000,
    dimensions: '61×73cm',
    medium: 'Oil on Canvas',
    category: 'Portrait',
    featured: false,
    description: {
      zh: '优雅的女子形象，带着神秘微笑，手中轻握折扇。',
      en: 'An elegant female figure with a mysterious smile, lightly holding a folding fan.',
    },
    images: [],
  },
  // Wu Guanzhong
  {
    _type: 'artwork',
    title: { zh: '江南水乡', en: 'Jiangnan Water Town' },
    slug: { current: 'wu-jiangnan' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_4' },
    price: 198000,
    dimensions: '70×140cm',
    medium: 'Oil on Canvas',
    category: 'Landscape',
    featured: true,
    description: {
      zh: '典型的吴冠中水墨现代化风格，简洁的线条与点彩描绘江南水乡的诗意。',
      en: 'Classic Wu Guanzhong modernization of ink style with concise lines and dot-coloring depicting the poetry of Jiangnan water towns.',
    },
    images: [],
  },
  {
    _type: 'artwork',
    title: { zh: '黄山云海', en: 'Yellow Mountain Sea of Clouds' },
    slug: { current: 'wu-yellow-mountain' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_4' },
    price: 258000,
    dimensions: '96×180cm',
    medium: 'Oil on Canvas',
    category: 'Landscape',
    featured: false,
    description: {
      zh: '黄山奇松与翻腾的云海，笔墨简练而气势磅礴。',
      en: 'The peculiar pines of Yellow Mountain and swirling clouds rendered with refined brushwork and grand momentum.',
    },
    images: [],
  },
  // Chang Yu
  {
    _type: 'artwork',
    title: { zh: '粉色裸女', en: 'Pink Nude' },
    slug: { current: 'chang-pink-nude' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_5' },
    price: 128000,
    dimensions: '87×122cm',
    medium: 'Oil on Canvas',
    category: 'Portrait',
    featured: true,
    description: {
      zh: '常玉标志性的粉色裸女，线条柔美，色彩淡雅。',
      en: 'Chang Yu signature pink nude with graceful lines and elegant, understated colors.',
    },
    images: [],
  },
  {
    _type: 'artwork',
    title: { zh: '五裸女', en: 'Five Nudes' },
    slug: { current: 'chang-five-nudes' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_5' },
    price: 380000,
    dimensions: '75×120cm',
    medium: 'Oil on Canvas',
    category: 'Portrait',
    featured: false,
    description: {
      zh: '五位裸女姿态各异，常玉独特的简约线条与装饰性构图。',
      en: 'Five nudes in varied poses with Chang Yu unique minimalist lines and decorative composition.',
    },
    images: [],
  },
  // Liu Haosu
  {
    _type: 'artwork',
    title: { zh: '黄山天下奇', en: 'Wonder of Yellow Mountain' },
    slug: { current: 'liu-yellow-mountain' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_6' },
    price: 186000,
    dimensions: '130×260cm',
    medium: 'Oil on Canvas',
    category: 'Landscape',
    featured: true,
    description: {
      zh: '刘海粟十上黄山后的创作，笔力雄健，气势恢宏。',
      en: 'Created after Liu Haosu climbed Yellow Mountain ten times, with robust brushwork and magnificent grandeur.',
    },
    images: [],
  },
  {
    _type: 'artwork',
    title: { zh: '飞流直下', en: 'Cascading Falls' },
    slug: { current: 'liu-cascading-falls' },
    artist: { _type: 'reference', _ref: 'ARTIST_ID_6' },
    price: 142000,
    dimensions: '90×180cm',
    medium: 'Oil on Canvas',
    category: 'Landscape',
    featured: false,
    description: {
      zh: '瀑布从山间奔涌而下，笔触豪放有力。',
      en: 'A waterfall rushes down from the mountains with bold and powerful brushstrokes.',
    },
    images: [],
  },
];
