export default {
  name: 'artwork',
  title: 'Artwork',
  type: 'document',
  fields: [
    { name: 'title', title: 'Title', type: 'object', fields: [
        { name: 'zh', title: 'Chinese', type: 'string' },
        { name: 'en', title: 'English', type: 'string' },
    ]},
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title.zh' }},
    { name: 'catalogCode', title: 'Catalog / source code', type: 'string',
      description: 'Stable unique code used to match local media folders, for example 80-120-13.'},
    { name: 'artist', title: 'Artist', type: 'reference', to: [{ type: 'artist' }]},
    { name: 'collectionType', title: 'Storefront collection', type: 'string', initialValue: 'new_collection',
      options: { list: [
        { title: 'New Collection', value: 'new_collection' },
        { title: 'Artist Collection', value: 'artist_collection' },
      ] },
      description: 'Legacy records remain in Artist Collection until their content and rights are reviewed.'},
    { name: 'productionModel', title: 'Production model', type: 'string', initialValue: 'hand_painted_to_order',
      options: { list: [
        { title: 'Hand-painted to order', value: 'hand_painted_to_order' },
        { title: 'Existing original artwork', value: 'original' },
      ] }},
    {
      name: 'seriesSlug',
      title: 'Primary storefront series',
      type: 'string',
      description: 'Stable merchandising series slug, for example ink-garden.',
    },
    {
      name: 'seriesRank',
      title: 'Series display rank',
      type: 'number',
      validation: (Rule: any) => Rule.integer().min(1),
    },
    {
      name: 'sizeProfile',
      title: 'Made-to-order size profile',
      type: 'string',
      options: {
        list: [
          { title: 'Square', value: 'square' },
          { title: '2:3', value: 'two-three' },
          { title: '3:4', value: 'three-four' },
          { title: 'Near-square', value: 'near-square' },
          { title: 'Panoramic', value: 'panoramic' },
        ],
      },
    },
    { name: 'rightsStatus', title: 'Rights status', type: 'string', initialValue: 'needs_review',
      options: { list: [
        { title: 'Approved for storefront', value: 'approved' },
        { title: 'Needs review', value: 'needs_review' },
        { title: 'Blocked', value: 'blocked' },
      ] }},
    { name: 'migrationStatus', title: 'Migration status', type: 'string', initialValue: 'needs_rights_review',
      options: { list: [
        { title: 'Ready', value: 'ready' },
        { title: 'Needs English copy', value: 'needs_copy' },
        { title: 'Needs images', value: 'needs_images' },
        { title: 'Needs rights review', value: 'needs_rights_review' },
        { title: 'Archive', value: 'archive' },
      ] }},
    { name: 'price', title: 'Base price (CNY)', type: 'number'},
    { name: 'allowCheckout', title: 'Allow direct checkout', type: 'boolean', initialValue: true,
      description: 'Turn off for price-on-request, oversized, reserved, or manually quoted works.'},
    { name: 'availability', title: 'Availability', type: 'string', initialValue: 'available',
      options: { list: ['available', 'reserved', 'sold'] }},
    { name: 'reservedUntil', title: 'Reserved until', type: 'datetime',
      description: 'Optional temporary hold expiry. Checkout is blocked while the artwork is reserved.'},
    { name: 'soldAt', title: 'Sold at', type: 'datetime',
      description: 'Set automatically or manually when the original work is sold.'},
    { name: 'soldOrderNumber', title: 'Sold order number', type: 'string',
      description: 'Internal order reference recorded when checkout marks this artwork sold.'},
    { name: 'dimensions', title: 'Dimensions', type: 'string', description: 'e.g. 60 x 80 cm'},
    { name: 'widthCm', title: 'Artwork width (cm)', type: 'number',
      description: 'Real artwork width in centimeters. Do not use image pixel width.'},
    { name: 'heightCm', title: 'Artwork height (cm)', type: 'number',
      description: 'Real artwork height in centimeters. Do not use image pixel height.'},
    { name: 'medium', title: 'Medium', type: 'string',
      options: { list: ['Oil on Canvas', 'Acrylic on Canvas', 'Oil on Panel', 'Mixed Media'] }},
    { name: 'category', title: 'Category', type: 'string',
      options: { list: ['Abstract', 'Landscape', 'Portrait', 'Figurative', 'Texture', 'Wabi-sabi', 'Minimalist'] }},
    { name: 'roomTypes', title: 'Recommended rooms', type: 'array', of: [{ type: 'string' }],
      options: { list: ['Living room', 'Bedroom', 'Dining room', 'Entryway', 'Office', 'Hospitality space'] }},
    { name: 'colorFamilies', title: 'Color families', type: 'array', of: [{ type: 'string' }],
      options: { list: ['Neutral', 'White', 'Black', 'Gray', 'Blue', 'Green', 'Red', 'Pink', 'Yellow', 'Orange', 'Earth tone', 'Multicolor'] }},
    { name: 'orientation', title: 'Orientation', type: 'string',
      options: { list: ['Portrait', 'Landscape', 'Square'] }},
    { name: 'styleTags', title: 'Additional style tags', type: 'array', of: [{ type: 'string' }],
      description: 'Optional storefront filters in addition to the primary category.'},
    { name: 'standardSizes', title: 'Made-to-order standard sizes', type: 'array',
      description: 'Required for hand-painted-to-order products. Prices are authoritative checkout prices in CNY.',
      of: [{
        type: 'object',
        name: 'standardSize',
        fields: [
          { name: 'label', title: 'Customer-facing label', type: 'string' },
          { name: 'widthCm', title: 'Width (cm)', type: 'number' },
          { name: 'heightCm', title: 'Height (cm)', type: 'number' },
          { name: 'priceCny', title: 'Price (CNY)', type: 'number' },
        ],
        preview: { select: { title: 'label', price: 'priceCny' }, prepare: ({ title, price }: any) => ({ title, subtitle: price ? `CNY ${price}` : 'Price required' }) },
      }]},
    { name: 'frameOptions', title: 'Finish / frame options', type: 'array',
      of: [{
        type: 'object',
        name: 'frameOption',
        fields: [
          { name: 'label', title: 'Customer-facing label', type: 'string' },
          { name: 'priceDeltaCny', title: 'Additional price (CNY)', type: 'number', initialValue: 0 },
        ],
        preview: { select: { title: 'label', delta: 'priceDeltaCny' }, prepare: ({ title, delta }: any) => ({ title, subtitle: `+ CNY ${Number(delta || 0)}` }) },
      }]},
    { name: 'creationWindow', title: 'Creation window', type: 'object', fields: [
        { name: 'zh', title: 'Chinese', type: 'string' },
        { name: 'en', title: 'English', type: 'string' },
      ], description: 'Example: Painted in 7-12 business days.'},
    { name: 'surfaceFinish', title: 'Surface / texture notes', type: 'string',
      description: 'Short storefront note such as layered texture, visible brushwork, matte surface, or glossy finish.'},
    { name: 'framingNotes', title: 'Framing notes', type: 'text',
      description: 'Optional advice for frame style, stretchers, float frame, or unframed display.'},
    { name: 'shippingProfile', title: 'Shipping profile', type: 'string',
      options: { list: ['Ships stretched', 'Ships rolled', 'Confirm before dispatch', 'Oversized freight'] },
      description: 'Optional internal/storefront shipping format guidance.'},
    { name: 'seoKeywords', title: 'SEO keywords', type: 'array', of: [{ type: 'string' }],
      description: 'Optional search phrases for collection and product content.'},
    { name: 'socialCaption', title: 'Social caption', type: 'text',
      description: 'Optional caption for Instagram, Pinterest, TikTok, or link-in-bio campaigns.'},
    { name: 'images', title: 'Images', type: 'array', of: [{ type: 'image', options: { hotspot: true } }]},
    { name: 'cloudflareImages', title: 'Cloudflare images', type: 'array',
      description: 'R2-hosted artwork image metadata. The website prefers these URLs and falls back to Sanity images.',
      of: [{ type: 'cloudflareAsset' }],
    },
    { name: 'productMedia', title: 'Product gallery media', type: 'array',
      description: 'Audited images and videos for the product gallery. Public display requires storefront approval.',
      of: [{ type: 'productMedia' }],
    },
    { name: 'description', title: 'Description', type: 'object', fields: [
        { name: 'zh', title: 'Chinese', type: 'text' },
        { name: 'en', title: 'English', type: 'text' },
    ]},
    { name: 'shortDescription', title: 'Short product description', type: 'object', fields: [
        { name: 'zh', title: 'Chinese', type: 'text', rows: 2 },
        { name: 'en', title: 'English', type: 'text', rows: 2 },
    ]},
    { name: 'artworkStory', title: 'Artwork story', type: 'object', fields: [
        { name: 'zh', title: 'Chinese', type: 'text' },
        { name: 'en', title: 'English', type: 'text' },
    ]},
    { name: 'materials', title: 'Materials and details', type: 'object', fields: [
        { name: 'zh', title: 'Chinese', type: 'text' },
        { name: 'en', title: 'English', type: 'text' },
    ]},
    { name: 'featured', title: 'Featured', type: 'boolean', initialValue: false},
  ],
}
