export default {
  name: 'artwork',
  title: 'Artwork',
  type: 'document',
  fields: [
    { name: 'title', title: 'Title', type: 'object', fields: [
        { name: 'zh', title: 'Chinese', type: 'string' },
        { name: 'en', title: 'English', type: 'string' },
    ]},
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'title.zh' }},
    { name: 'artist', title: 'Artist', type: 'reference', to: [{ type: 'artist' }]},
    { name: 'price', title: 'Base price (CNY)', type: 'number'},
    { name: 'dimensions', title: 'Dimensions', type: 'string', description: 'e.g. 60 x 80 cm'},
    { name: 'medium', title: 'Medium', type: 'string',
      options: { list: ['Oil on Canvas', 'Acrylic on Canvas', 'Oil on Panel', 'Mixed Media'] }},
    { name: 'category', title: 'Category', type: 'string',
      options: { list: ['Abstract', 'Landscape', 'Portrait', 'Texture', 'Wabi-sabi', 'Minimalist'] }},
    { name: 'roomTypes', title: 'Recommended rooms', type: 'array', of: [{ type: 'string' }],
      options: { list: ['Living room', 'Bedroom', 'Dining room', 'Entryway', 'Office', 'Hospitality space'] }},
    { name: 'colorFamilies', title: 'Color families', type: 'array', of: [{ type: 'string' }],
      options: { list: ['Neutral', 'White', 'Black', 'Gray', 'Blue', 'Green', 'Red', 'Pink', 'Yellow', 'Orange', 'Earth tone', 'Multicolor'] }},
    { name: 'orientation', title: 'Orientation', type: 'string',
      options: { list: ['Portrait', 'Landscape', 'Square'] }},
    { name: 'surfaceFinish', title: 'Surface / texture notes', type: 'string',
      description: 'Short storefront note such as layered texture, visible brushwork, matte surface, or glossy finish.'},
    { name: 'framingNotes', title: 'Framing notes', type: 'text',
      description: 'Optional advice for frame style, stretchers, float frame, or unframed display.'},
    { name: 'shippingProfile', title: 'Shipping profile', type: 'string',
      options: { list: ['Ships stretched', 'Ships rolled', 'Confirm before dispatch', 'Oversized freight'] },
      description: 'Optional internal/storefront shipping format guidance.'},
    { name: 'seoKeywords', title: 'SEO keywords', type: 'array', of: [{ type: 'string' }],
      description: 'Optional search phrases for collection and product content.'},
    { name: 'socialCaption', title: 'Social caption', type: 'text',
      description: 'Optional caption for Instagram, Pinterest, TikTok, or link-in-bio campaigns.'},
    { name: 'images', title: 'Images', type: 'array', of: [{ type: 'image', options: { hotspot: true } }]},
    { name: 'description', title: 'Description', type: 'object', fields: [
        { name: 'zh', title: 'Chinese', type: 'text' },
        { name: 'en', title: 'English', type: 'text' },
    ]},
    { name: 'featured', title: 'Featured', type: 'boolean', initialValue: false},
  ],
}
